repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
        args: ['--fix=no']
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: detect-private-key

-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.1
    hooks:
    -   id: doc8
        name: doc8
        description: This hook runs doc8 for linting docs
        entry: python -m doc8
        language: python
        files: \.rst$

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]
